import argparse
import gc
import os

import pandas as pd
from cohort_builder import build_and_save_cohorts
from processing_pipeline.extraction.extractor import MIMICExtractor
from trajectory_builder import (
    build_trajectories,
    load_and_filter_chunked,
    load_measurement_mappings,
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="MIMIC-IV Sepsis Prediction Data Pipeline"
    )
    parser.add_argument(
        "--config",
        type=str,
        default="config.json",
        help="Path to pipeline configuration file",
    )
    parser.add_argument(
        "-u",
        "--username",
        help="MIMIC Database Username (for extraction)",
        type=str,
        default="",
    )
    parser.add_argument(
        "-p",
        "--password",
        help="MIMIC Database Password (for extraction)",
        type=str,
        default="",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    # Safe defaults config simulation
    config = {
        "extraction": {
            "metadata_path": "src/data_processing/processing_pipeline/extraction/extraction_metadata.json",
            "export_dir": "data/processed_files",
        },
        "cohort": {
            "input_dir": "data/processed_files",
            "output_dir": "data/processed_files",
            "save_intermediate": True,
        },
        "trajectories": {
            "input_dir": "data/processed_files",
            "output_dir": "data/processed_files",
            "missing_threshold": 0.8,
            "timestep": 4,
            "window_before": 24,
            "window_after": 72,
        },
    }

    try:
        print("=== PHASE 1: EXTRACTION ===")
        if args.username and args.password:
            extractor = MIMICExtractor(
                user=args.username,
                password=args.password,
                export_dir=config["extraction"]["export_dir"],
            )
            extractor.extract_all(config["extraction"]["metadata_path"])
            extractor.close()
        else:
            print("Skipping database extraction as no credentials were provided.")
            print(
                "Assuming raw tables already exist in: ",
                config["extraction"]["export_dir"],
            )

        print("\n=== PHASE 2: STATIC COHORT GENERATION ===")
        if not os.path.exists(f"{config['cohort']['output_dir']}/cohort.csv"):
            onset, bacterio, demog, raw_data_dict = build_and_save_cohorts(
                config["cohort"]
            )
            del bacterio, demog, raw_data_dict
            gc.collect()
        else:
            print("Cohort file already exists. Loading valid onset anchors...")
            onset = pd.read_csv(
                f"{config['cohort']['output_dir']}/onset.csv", sep="|", low_memory=False
            )

        print("\n=== PHASE 3: TRAJECTORY & MEASUREMENT FORMATTING ===")
        print("Loading measurements mappings...")
        measurements, code_to_concept, hold_times = load_measurement_mappings()

        valid_stays = onset["stay_id"].unique()
        input_dir = config["trajectories"]["input_dir"]

        # Load high volume chunked data memory-safely
        # Note: In trajectory_builder, load_and_filter_chunked expects the filename and valid_stays
        print("Loading Chartevents chunked...")
        ce_df = load_and_filter_chunked(
            "chartevents.csv", valid_stays, onset, time_col="charttime"
        )

        print("Loading Labevents chunked...")
        # labu was generated by cohort builder above
        lab_df = load_and_filter_chunked(
            "labu.csv", valid_stays, onset, time_col="charttime"
        )

        print("Loading Mechanical Ventilation data chunked...")
        mv_df = load_and_filter_chunked(
            "mechvent.csv", valid_stays, onset, time_col="starttime"
        )

        # Dummy data dict to pass through structural standardizer logic (the notebook did this)
        data_dict = {
            "demog": pd.read_csv(
                f"{input_dir}/demog_processed.csv", sep="|", low_memory=False
            )
        }
        onset = onset.rename(
            columns={"anchor_time": "suspected_infection_time_sec"}
        )  # align naming

        print(
            f"Building {config['trajectories']['timestep']}-hour interval trajectories..."
        )
        final_trajectories = build_trajectories(
            onset,
            valid_stays,
            data_dict,
            ce_df,
            lab_df,
            mv_df,
            code_to_concept,
            hold_times,
            config["trajectories"],
        )

        # We will add saving the fastparquet here
        out_path = f"{config['trajectories']['output_dir']}/patient_timeseries_cleaned_final.parquet"
        print(f"Saving final cleaned FAIR dataset to: {out_path}")
        final_trajectories.to_parquet(out_path, engine="fastparquet")
        print("PIPELINE COMPLETE.")

    except Exception as e:
        print(f"Pipeline Failed: {e}")


if __name__ == "__main__":
    main()
