import argparse
import gc
import os

import pandas as pd
from cohort_builder import build_and_save_cohorts
from processing_pipeline.extraction.extractor import MIMICExtractor
from trajectory_builder import (
    build_trajectories,
    load_and_filter_chunked,
    load_measurement_mappings,
)


def parse_args():
    """Parse command-line arguments for the pipeline."""
    parser = argparse.ArgumentParser(
        description="MIMIC-IV Sepsis Prediction Data Pipeline"
    )
    parser.add_argument(
        "--config",
        type=str,
        default="config.json",
        help="Path to pipeline configuration file",
    )
    parser.add_argument(
        "--raw-data-dir",
        type=str,
        default="",
        help=(
            "Path to raw MIMIC-IV directory containing hosp/ and icu/ subdirectories "
            "(e.g. data/raw/mimic-iv-3.1). Required for Phase 1 extraction; "
            "omit if extracted CSVs already exist."
        ),
    )
    return parser.parse_args()


def main():
    """Execute the full MIMIC-IV sepsis data pipeline end-to-end."""
    args = parse_args()

    # Safe defaults config simulation
    config = {
        "extraction": {
            "metadata_path": (
                "src/data_processing/processing_pipeline/"
                "extraction/extraction_metadata.json"
            ),
            "export_dir": "data/processed_files",
        },
        "cohort": {
            "input_dir": "data/processed_files",
            "output_dir": "data/processed_files",
            "save_intermediate": True,
        },
        "trajectories": {
            "input_dir": "data/processed_files",
            "output_dir": "data/processed_files",
            "missing_threshold": 0.8,
            "timestep": 4,
            "window_before": 24,
            "window_after": 72,
        },
    }

    try:
        print("=== PHASE 1: EXTRACTION ===")
        if args.raw_data_dir:
            extractor = MIMICExtractor(
                raw_data_dir=args.raw_data_dir,
                export_dir=config["extraction"]["export_dir"],
            )
            extractor.extract_all(config["extraction"]["metadata_path"])
            extractor.close()
        else:
            print("Skipping extraction (no --raw-data-dir provided).")
            print(
                "Assuming CSV files already exist in:",
                config["extraction"]["export_dir"],
            )

        print("\n=== PHASE 2: STATIC COHORT GENERATION ===")
        if not os.path.exists(f"{config['cohort']['output_dir']}/cohort.csv"):
            onset, bacterio, demog, raw_data_dict = build_and_save_cohorts(
                config["cohort"]
            )
            del bacterio, demog, raw_data_dict
            gc.collect()
        else:
            print("Cohort file already exists. Loading cohort...")
            onset = pd.read_csv(
                f"{config['cohort']['output_dir']}/cohort.csv",
                sep="|",
                low_memory=False,
            )

        print("\n=== PHASE 3: TRAJECTORY & MEASUREMENT FORMATTING ===")
        print("Loading measurements mappings...")
        measurements, code_to_concept, hold_times = load_measurement_mappings()

        valid_stays = onset["stay_id"].unique()

        # Load high volume chunked data memory-safely
        print("Loading Chartevents chunked...")
        ce_df = load_and_filter_chunked(
            "chartevents.csv", valid_stays, onset, time_col="charttime"
        )

        print("Loading Labevents chunked...")
        # labu was generated by cohort builder above
        lab_df = load_and_filter_chunked(
            "labu.csv", valid_stays, onset, time_col="charttime"
        )

        print("Loading Mechanical Ventilation data chunked...")
        mv_df = load_and_filter_chunked(
            "mechvent.csv", valid_stays, onset, time_col="charttime"
        )

        # data_dict passes static demog info and secondary tables to
        # the trajectory standardiser
        print("Loading secondary tables (fluid, vaso, UO, abx)...")
        data_dict = {
            "demog": load_and_filter_chunked("demog_processed.csv", valid_stays),
            "abx": load_and_filter_chunked("abx_processed.csv", valid_stays),
            "fluid": load_and_filter_chunked("fluid.csv", valid_stays),
            "vaso": load_and_filter_chunked("vaso.csv", valid_stays),
            "UO": load_and_filter_chunked("uo.csv", valid_stays),
        }

        print(
            f"Building {config['trajectories']['timestep']}-hour "
            "interval trajectories..."
        )
        final_trajectories = build_trajectories(
            onset,
            valid_stays,
            data_dict,
            ce_df,
            lab_df,
            mv_df,
            code_to_concept,
            hold_times,
            config["trajectories"],
        )

        del ce_df, lab_df, mv_df, data_dict, onset

        out_dir = config["trajectories"]["output_dir"]
        out_path = f"{out_dir}/patient_timeseries_cleaned_final.parquet"
        print(f"Saving final cleaned FAIR dataset to: {out_path}")
        final_trajectories.to_parquet(out_path, engine="fastparquet")
        print("PIPELINE COMPLETE.")

    except Exception as e:
        print(f"Pipeline Failed: {e}")


if __name__ == "__main__":
    main()
