import argparse
import gc
import os

import pandas as pd
import yaml
from cohort_builder import build_and_save_cohorts
from extraction.extractor import MIMICExtractor
from trajectory_builder import (
    build_trajectories,
    load_and_filter_chunked,
    load_measurement_mappings,
)


def parse_args():
    """Parse command-line arguments for the pipeline."""
    parser = argparse.ArgumentParser(
        description="MIMIC-IV Sepsis Prediction Data Pipeline"
    )
    parser.add_argument(
        "--config",
        type=str,
        default="src/data_processing/config.yaml",
        help="Path to pipeline configuration YAML file",
    )
    parser.add_argument(
        "--raw-data-dir",
        type=str,
        default="",
        help=(
            "Path to raw MIMIC-IV directory containing hosp/ and icu/ subdirectories "
            "(e.g. data/raw/mimic-iv-3.1). Required for Phase 1 extraction; "
            "omit if extracted CSVs already exist."
        ),
    )
    return parser.parse_args()


def main():
    """Execute the full MIMIC-IV sepsis data pipeline end-to-end."""
    args = parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    try:
        print("=== PHASE 1: EXTRACTION ===")
        if args.raw_data_dir:
            extractor = MIMICExtractor(
                raw_data_dir=args.raw_data_dir,
                export_dir=cfg["paths"]["extracted_dir"],
            )
            extractor.extract_all(cfg["paths"]["extraction_metadata"])
            extractor.close()
        else:
            print("Skipping extraction (no --raw-data-dir provided).")
            print("Assuming CSV files already exist in:", cfg["paths"]["extracted_dir"])

        print("\n=== PHASE 2: STATIC COHORT GENERATION ===")
        cohort_path = os.path.join(cfg["paths"]["processed_dir"], "cohort.csv")
        if not os.path.exists(cohort_path):
            cohort, bacterio, demog, raw_data_dict = build_and_save_cohorts(
                cfg["cohort"],
                cfg["paths"],
            )
            del bacterio, demog, raw_data_dict
            gc.collect()
        else:
            print("Cohort file already exists. Loading cohort...")
            cohort = pd.read_csv(
                cohort_path,
                sep="|",
                low_memory=False,
            )

        print("\n=== PHASE 3: TRAJECTORY & MEASUREMENT FORMATTING ===")
        print("Loading measurements mappings...")
        measurements, code_to_concept, hold_times = load_measurement_mappings(
            path=cfg["trajectories"]["measurement_mappings_path"]
        )

        valid_stays = cohort["stay_id"].unique()

        chunk_size = cfg["trajectories"]["chunk_size"]

        # Load high volume chunked data memory-safely
        print("Loading Chartevents chunked...")
        ce_df = load_and_filter_chunked(
            os.path.join(cfg["paths"]["extracted_dir"], "chartevents.csv"),
            valid_stays,
            cohort,
            time_col="charttime",
            chunk_size=chunk_size,
        )

        print("Loading Labevents chunked...")
        # labu was generated by cohort builder above
        lab_df = load_and_filter_chunked(
            os.path.join(cfg["paths"]["extracted_dir"], "labu.csv"),
            valid_stays,
            cohort,
            time_col="charttime",
            chunk_size=chunk_size,
        )

        print("Loading Mechanical Ventilation data chunked...")
        mv_df = load_and_filter_chunked(
            os.path.join(cfg["paths"]["extracted_dir"], "mechvent.csv"),
            valid_stays,
            cohort,
            time_col="charttime",
            chunk_size=chunk_size,
        )

        # data_dict passes static demog info and secondary tables to
        # the trajectory standardiser
        print("Loading secondary tables (fluid, vaso, UO, abx)...")
        data_dict = {
            "demog": load_and_filter_chunked(
                os.path.join(cfg["paths"]["extracted_dir"], "demog_processed.csv"),
                valid_stays,
                chunk_size=chunk_size,
            ),
            "abx": load_and_filter_chunked(
                os.path.join(cfg["paths"]["extracted_dir"], "abx_processed.csv"),
                valid_stays,
                chunk_size=chunk_size,
            ),
            "fluid": load_and_filter_chunked(
                os.path.join(cfg["paths"]["extracted_dir"], "fluid.csv"),
                valid_stays,
                chunk_size=chunk_size,
            ),
            "vaso": load_and_filter_chunked(
                os.path.join(cfg["paths"]["extracted_dir"], "vaso.csv"),
                valid_stays,
                chunk_size=chunk_size,
            ),
            "UO": load_and_filter_chunked(
                os.path.join(cfg["paths"]["extracted_dir"], "uo.csv"),
                valid_stays,
                chunk_size=chunk_size,
            ),
        }

        print(
            f"Building {cfg['trajectories']['timestep']}-hour interval trajectories..."
        )
        final_trajectories = build_trajectories(
            cohort,
            valid_stays,
            data_dict,
            ce_df,
            lab_df,
            mv_df,
            code_to_concept,
            hold_times,
            cfg["trajectories"],
            cfg["paths"]["processed_dir"],
        )

        del ce_df, lab_df, mv_df, data_dict, cohort

        out_path = os.path.join(
            cfg["paths"]["processed_dir"], cfg["paths"]["output_filename"]
        )
        print(f"Saving dataset to: {out_path}")
        final_trajectories.to_parquet(out_path, engine="fastparquet")
        print("PIPELINE COMPLETE.")

    except Exception as e:
        print(f"Pipeline Failed: {e}")


if __name__ == "__main__":
    main()
